name: Maven Build with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4. Build with Maven and run SonarQube
      - name: Build with Maven and run SonarQube
        working-directory: jacoco-multimodule-maven
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=YOUR_PROJECT_KEY \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.GITHUB }}
